apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: z8r
    tier: daemon
  name: node-daemon
  namespace: z8r
spec:
  selector:
    matchLabels:
      app: z8r
      tier: daemon
  template:
    metadata:
      labels:
        app: z8r
        tier: daemon
    spec:
      serviceAccount: z8r
      nodeSelector:
        zfs.replication.takutakahashi.dev: "true"
      containers:
      - image: takutakahashi/z8r:v0.2.0
        imagePullPolicy: Always
        name: app
        securityContext:
          privileged: true
        command:
        - /entrypoint_daemon.sh
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: replicator
  name: replicator
  namespace: z8r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replicator
  template:
    metadata:
      labels:
        app: replicator
    spec:
      serviceAccount: z8r
      containers:
      - image: takutakahashi/z8r:v0.2.0
        imagePullPolicy: Always
        name: app
        env:
          - name: DEBUG
            value: "false"
        command:
        - /entrypoint_replicator.sh
