kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: z8r-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: z8r-role-binding
  namespace: z8r
subjects:
- kind: ServiceAccount
  name: z8r
  namespace: z8r
roleRef:
  kind: ClusterRole
  name: z8r-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: z8r
  namespace: z8r
