apiVersion: v1
kind: Service
metadata:
  labels:
    app: replicator
  name: replicator
  namespace: z8r
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: replicator
